version: yml-{build}
environment:
  CHANNEL: stable
  MODE: --release
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TARGET: i686-pc-windows-msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TARGET: x86_64-pc-windows-gnu
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TARGET: i686-pc-windows-gnu
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - TARGET: x86_64-unknown-linux-gnu
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004

cache:
  - '%USERPROFILE%\.cargo'

install:
- cmd: 'C:\cygwin64\setup-x86_64.exe --no-admin -q -P sng'
- sh: 'sudo apt-get -yq install sng'
- ps: '$env:SNG = if (Test-Path "/usr/bin/sng") {"/usr/bin/sng"} elseif (Test-Path "C:\cygwin64\bin\sng.exe") {"C:\cygwin64\bin\sng.exe"} else {exit 1}'
- ps: '& $env:SNG -V'

- cmd: |
    appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    rustup-init -y --default-toolchain %CHANNEL% --default-host %TARGET%
    set PATH=%PATH%;%USERPROFILE%\.cargo\bin
- sh: |
    curl https://sh.rustup.rs -sSf >rustup.sh
    chmod +x rustup.sh
    ./rustup.sh -y --default-toolchain $CHANNEL --default-host $TARGET
    source $HOME/.cargo/env
- ps: '& cargo -V'

build_script:
- cmd: 'cargo build %MODE%'
- sh: 'cargo build $MODE'

- cmd: '7z a target\release\png_inflate.exe.gz target\release\png_inflate.exe'
- sh: 'gzip -c target/release/png_inflate --keep > target/release/png_inflate.gz'

test_script:
- cmd: 'cargo test %MODE%'
- sh: 'cargo test $MODE'

- ps: './target/release/png_inflate --version'
artifacts:
- path: target\release\png_inflate.exe.gz
- path: target\release\png_inflate.gz
