name: Tests
on: [push]
jobs:
  ubuntu:
    strategy:
      matrix:
        mode: ["", "--release"]
    runs-on: ubuntu-latest
    env:
      SNG: /usr/bin/sng
    steps:
    - name: Get Dependencies
      run: 'sudo apt-get -yq install sng'
    - uses: actions/checkout@v1
    - name: Run tests
      run: 'cargo test --verbose ${{matrix.mode}}'
  windows:
    strategy:
      matrix:
        mode: ["", "--release"]
    runs-on: windows-latest
    env:
      SNG: C:\tools\cygwin\bin\sng.exe
    steps:
    - name: Get Dependencies
      shell: pwsh
      run: |
        & choco install Cygwin
        & C:\tools\cygwin\cygwinsetup.exe --no-admin -q -P sng
    - uses: actions/checkout@v1
    - name: Build
      run: 'cargo build --verbose'
    - name: Run tests
      run: 'cargo test --verbose ${{matrix.mode}}'
